use rmucha_a
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Paycheck','Pavo cristatus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Young Man with a Horn','Alouatta seniculus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Quicksand','Ammospermophilus nelsoni')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Sun, The (Solntse)','Graspus graspus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Unfinished Sky','Alligator mississippiensis')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Last Lions, The','Macropus fuliginosus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('City of Lost Children, The (Cité des enfants perdus, La)','Panthera onca')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Killer Is Loose, The','Tachyglossus aculeatus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Blind Pig Who Wants to Fly (Babi buta yang ingin terbang)','Chionis alba')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Foster Brothers, The (Süt kardesler)','Hystrix indica')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Silver Bullet (Stephen King''s Silver Bullet)','Hippopotamus amphibius')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Sex and Fury (Furyô anego den: Inoshika Ochô)','Alouatta seniculus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('My Big Fat Greek Wedding','Melophus lathami')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Bleak House','Canis mesomelas')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Beauty Is Embarrassing','Theropithecus gelada')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('White Oleander','Cracticus nigroagularis')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Tristram Shandy: A Cock and Bull Story','Naja nivea')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Wanderers','Gymnorhina tibicen')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Gone Fishin''','Felis chaus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Rollercoaster','Estrilda erythronotos')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Man Who Laughs, The','Coluber constrictor')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Inbetween Worlds','Pelecans onocratalus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Pride and Prejudice','Felis silvestris lybica')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Moving','Chionis alba')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Ivul','Felis silvestris lybica')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Moonbase','Axis axis')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Lassie Come Home','Delphinus delphis')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('We''re No Angels','Antilocapra americana')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('Grapes of Death, The (Raisins de la mort, Les)','Hymenolaimus malacorhynchus')
INSERT INTO Conferences (ConferenceName, ConferenceDescription)
VALUES('In a Dark Place','Coracias caudata')
