INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('83','0.4','1')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('73','0.3','1')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('63','0.2','1')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.5','2')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.4','2')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.3','2')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.2','2')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('67','0.3','3')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('57','0.2','3')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('123','0.5','4')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('113','0.4','4')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('103','0.3','4')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('93','0.2','4')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('59','0.5','5')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('49','0.4','5')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('39','0.3','5')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('29','0.2','5')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('114','0.70000005','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('104','0.6','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('94','0.5','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('84','0.4','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('74','0.3','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('64','0.2','6')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('65','0.4','7')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('55','0.3','7')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('45','0.2','7')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.2','8')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('97','0.4','9')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('87','0.3','9')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('77','0.2','9')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('97','0.5','11')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('87','0.4','11')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('77','0.3','11')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('67','0.2','11')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('64','0.5','12')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('54','0.4','12')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('44','0.3','12')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('34','0.2','12')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('79','0.4','13')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('69','0.3','13')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('59','0.2','13')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('70','0.5','14')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('60','0.4','14')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('50','0.3','14')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('40','0.2','14')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('96','0.5','16')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('86','0.4','16')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.3','16')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.2','16')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('67','0.3','17')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('57','0.2','17')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('99','0.4','19')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('89','0.3','19')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('79','0.2','19')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('118','0.6','20')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('108','0.5','20')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('98','0.4','20')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.3','20')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.2','20')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('85','0.4','21')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('75','0.3','21')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('65','0.2','21')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('62','0.4','22')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('52','0.3','22')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('42','0.2','22')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('37','0.4','23')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('27','0.3','23')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('17','0.2','23')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('45','0.2','24')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('47','0.3','25')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('37','0.2','25')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('95','0.4','26')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('85','0.3','26')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('75','0.2','26')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('98','0.5','27')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.4','27')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.3','27')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.2','27')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.3','28')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.2','28')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('77','0.70000005','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('67','0.6','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('57','0.5','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('47','0.4','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('37','0.3','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('27','0.2','29')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('42','0.5','30')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('32','0.4','30')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('22','0.3','30')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('12','0.2','30')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.5','31')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.4','31')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('56','0.3','31')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('46','0.2','31')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('44','0.2','32')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('94','0.5','33')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('84','0.4','33')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('74','0.3','33')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('64','0.2','33')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('16','0.2','34')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.4','35')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.3','35')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.2','35')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('94','0.2','36')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.6','38')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.5','38')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.4','38')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.3','38')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('48','0.2','38')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('64','0.5','39')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('54','0.4','39')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('44','0.3','39')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('34','0.2','39')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('22','0.2','40')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('93','0.6','41')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('83','0.5','41')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('73','0.4','41')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('63','0.3','41')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('53','0.2','41')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('24','0.2','42')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('96','0.5','43')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('86','0.4','43')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.3','43')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.2','43')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('84','0.3','44')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('74','0.2','44')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('137','0.5','45')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('127','0.4','45')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('117','0.3','45')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('107','0.2','45')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('46','0.3','46')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('36','0.2','46')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('54','0.4','47')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('44','0.3','47')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('34','0.2','47')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('133','0.8','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('123','0.70000005','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('113','0.6','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('103','0.5','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('93','0.4','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('83','0.3','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('73','0.2','49')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('71','0.5','50')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('61','0.4','50')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('51','0.3','50')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('41','0.2','50')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('64','0.4','51')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('54','0.3','51')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('44','0.2','51')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('80','0.4','52')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('70','0.3','52')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('60','0.2','52')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.3','53')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.2','53')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('86','0.6','54')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.5','54')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.4','54')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('56','0.3','54')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('46','0.2','54')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('51','0.3','55')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('41','0.2','55')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.6','56')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.5','56')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.4','56')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.3','56')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('48','0.2','56')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('139','0.6','57')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('129','0.5','57')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('119','0.4','57')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('109','0.3','57')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('99','0.2','57')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('65','0.4','58')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('55','0.3','58')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('45','0.2','58')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('105','0.4','59')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('95','0.3','59')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('85','0.2','59')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('32','0.3','61')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('22','0.2','61')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('119','0.8','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('109','0.70000005','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('99','0.6','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('89','0.5','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('79','0.4','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('69','0.3','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('59','0.2','62')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('35','0.4','63')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('25','0.3','63')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('15','0.2','63')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.2','64')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('78','0.5','65')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('68','0.4','65')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('58','0.3','65')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('48','0.2','65')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('118','0.5','66')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('108','0.4','66')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('98','0.3','66')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('88','0.2','66')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('86','0.5','67')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.4','67')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.3','67')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('56','0.2','67')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('60','0.4','68')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('50','0.3','68')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('40','0.2','68')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('28','0.4','69')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('18','0.3','69')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('8','0.2','69')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('59','0.2','70')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('76','0.6','71')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('66','0.5','71')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('56','0.4','71')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('46','0.3','71')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('36','0.2','71')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('69','0.5','72')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('59','0.4','72')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('49','0.3','72')
INSERT INTO TimeDiscounts (NumOfDaysBefore, Discount, ConferenceEditionID)
VALUES('39','0.2','72')
