INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Vittariaceae','Tufted Lineleaf Fern','Ganny Broader','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Needlegrass','Tyne Karpfen','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Primulaceae','Cowslip Primrose','Silas Dartan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Shield Lichen','Jarid Thomsson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Godfry Trower','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lichinaceae','Thermutis Lichen','Chrisse Yate','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Fireweed','Anette Jorez','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Betulaceae','American Hornbeam','Maren Rattray','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Sematophyllaceae','Maryland Sematophyllum Moss','Shep Darlasson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arthopyreniaceae','Lyre Shell Lichen','Alexandro Pincked','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cactaceae','Cushion Foxtail Cactus','Kaitlin Shropshire','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Calycanthaceae','Eastern Sweetshrub','Celestina Joblin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hippocastanaceae','Japanese Horse Chestnut','Hogan Mockler','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fissidentaceae','Fissidens Moss','Nelson Trinder','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Haresfoot Locoweed','Ranice Kellick','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pedaliaceae','Escorzonera','Emlyn McIlvoray','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Talus Springparsley','Webster Dellatorre','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Field Blackberry','Lucretia Beddo','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Mountain Goldenbanner','Chase Messiter','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Axilflower','Court Cuchey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hydrocharitaceae','Brazilian Waterweed','Jdavie Van De Cappelle','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Cymbopogon Grass','Jackie Dodgshun','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Bog Yellowcress','Aeriell MacKeig','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Clasping Heliotrope','Mignonne Maddison','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Douglas'' Buckwheat','Lethia Kleinsmuntz','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apocynaceae','Trachelospermum','Odille Slocumb','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Ashe''s Calamint','Domini Torbet','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Bolander''s Mule-ears','Homer Breyt','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Kaffir Potato','Laurette Breissan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lichinaceae','Demangeon''s Phylliscum Lichen','Doris Kelloch','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Sneezeweed','Reagan Belham','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','White Bryony','Brigitta Dodman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Rinodina Lichen','Rosanna Galgey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','West Indian Sage','Chance Ficken','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Knotted Pearlwort','Nyssa Skirvane','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Yellow Gilia','Claudio Trenchard','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Crassulaceae','Nevius'' Stonecrop','Drucy Skillanders','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Rurik McLagain','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Big Chickweed','Jocelyn Shelf','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Mouse-ear Chickweed','Danell Kainz','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lobariaceae','Lung Lichen','Gaspard Kesteven','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Broadleaf Panicum','Mack Theseira','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhamnaceae','Urban''s Nakedwood','Brendis Millions','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Wreath Lichen','Abbie O''Heneghan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cuscutaceae','Cusp Dodder','Shep Scully','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Fringed Windmill Grass','Murvyn Cleynaert','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Elegant Zinnia','Idalina Bulley','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Spotted Beebalm','Jacky Oakland','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pteridaceae','Slender Brake','Gordie Westberg','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Goatgrass','Brooke Santorini','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Forked Hareleaf','Jamil Rodolico','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pyrenulaceae','Macoun''s Wart Lichen','Muire Worling','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Maize','Kim Spykings','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Geraniaceae','Veiny Geranium','Flossie Kneal','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Fonio','Thane Varns','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Magnoliaceae','Tuliptree','Alec Lesurf','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','White Thoroughwort','Tera Waterhowse','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Geraniaceae','Zonal Geranium','Zaria Artis','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Broadleaf Wild Leek','Neddy Headech','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Theaceae','Ternstroemia','Osbert MacGettigen','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Nepal Physciella','Levey Ribchester','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Lowland Blackberry','Sherm Nyland','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Porpidiaceae','Bellemerea Lichen','Sven Vouls','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Parry''s Mallow','Ebony Slisby','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Kauai Bur Cucumber','Bernadene Matieu','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Louisiana Goldenrod','Christalle Sweed','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Kenilworth Ivy','Ferne Furmenger','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fagaceae','Tanoak','Kally McIlenna','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Western Wallflower','Ado Mallock','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Portulacaceae','Brandegee''s Springbeauty','Mandy Lummasana','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Curly Dock','Alvie Everton','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Oleaceae','Devilwood','Kaiser Domenge','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Gibson''s Cyanea','Louella Strothers','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Urban''s Sandmat','Shena Bugg','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Missouri Milkvetch','Tristam Anelay','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Good King Henry','Rolando MacKaig','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Juda''s Bush','Wes Pocklington','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Moleplant','Sonja Cartin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Hardham''s Bedstraw','Holly-anne Brownell','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Indian Flatsedge','Cristiano Caulwell','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Field Sagewort','Marcela Murrigan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Capparaceae','Tropical Spiderflower','Miguela Lecordier','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Icacinaceae','Ngmui','Stormie Skiggs','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Hardheads','Nancee Huie','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pottiaceae','Acaulon Moss','Nev Dinesen','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Menispermaceae','Velvetleaf','Stefa Gibbe','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Pentaclethra','Borg Galbraith','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Hybrid Rose','Guglielma Ornelas','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Alpine Bittercress','Xylia Deverose','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Snow Arnica','Ripley Louiset','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Tropical Puff','Hendrick Casassa','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Rough Dubautia','Justino Epps','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Aleutian Brome','Melantha Kanter','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Melianthaceae','Melianthus','Sylas Dossit','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Arctic Rinodina Lichen','Ezmeralda Nunes Nabarro','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Urticaceae','Puerto Rico Clearweed','Cathi Meigh','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Brouard''s Rim Lichen','Rossie Dradey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Proatriplex','Read Duncan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Soft Goldenaster','Karina Norway','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Kamchatka Spikerush','Al Goodliffe','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Ecotone Blackberry','Anna-maria Muckloe','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Eggleaf Coraldrops','Evelin Wilcox','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Purple Poppymallow','Bartlett Mirfield','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brachytheciaceae','Nelson''s Brachythecium Moss','Maridel Rosone','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Iridaceae','Nuttall''s Pleatleaf','Leonanie Roach','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Hooker Bugseed','Rene Holstein','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Freckled Milkvetch','Wes Vipan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Pale Giant Hyssop','Efren Alldritt','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Woollypod Milkvetch','Riobard Roughsedge','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Panicled Sandmallow','Gates Pech','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Saltbush','Petey Scholcroft','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Kaibab Suncup','Noll Fourman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Kern Mallow','Alis Anfrey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Florida Pineland Spurge','Norrie Rowsel','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cupressaceae','Western Juniper','Martin Golborn','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Theophrastaceae','Chirriador','Tessy Chyuerton','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Agavaceae','Indian Bowstring Hemp','Lauren Friel','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Siberian Dock','Bax Rouby','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Arctic Rattlebox','Broderick Luchelli','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Seaside Amaranth','Cob Noakes','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Cucubano','Kort Brastead','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Phytolaccaceae','Guinea Henweed','Clarke Flaxon','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Licorice Weed','Karil Sephton','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Western Sweetvetch','Randolph Van de Velde','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Kern Larkspur','Denny Stanbrooke','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pinaceae','Subalpine Fir','Sandra Lowey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Acarosporaceae','Sarcosagium Lichen','Gaston Satteford','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cuscutaceae','Trans-pecos Dodder','Mathe Spackman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhizocarpaceae','Distinct Map Lichen','Clarine Abbiss','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Lesser Hawkbit','Windham Tatlowe','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Portulacaceae','Streambank Springbeauty','Lawry McGoldrick','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Holm''s Reedgrass','Tova Sandwith','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Cotorrilla','Joel Van der Hoeven','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Capparaceae','Oxystylis','Lyell Rought','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Rubber Rabbitbrush','Georg Clayfield','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Low Silverbush','Alejandrina Gjerde','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Lone Fleabane','Rochella Desantis','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','American Plum','Holmes Bartoleyn','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Hebe','Clementine Noonan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Burrdock','Keslie Milne','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Soft Phlox','Malena Petrashkov','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Barbasco','Bryana Scotson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','False Spiraea','Cthrine Angliss','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Roving Sailor','Cobby Drillingcourt','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Myrtaceae','Guavaberry','Nicholle Eiler','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Porter''s Reedgrass','Trever Faires','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Solanaceae','Cypresshead Groundcherry','Shannon Blackledge','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Aspleniaceae','Pamohe','Stefania Robillart','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Reed','Othelia Trustey','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Oxalidaceae','Carambola','Jay Stringman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Myrtaceae','Burgan','Datha Plackstone','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Volcan''s Fuchsia','Schuyler Assad','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Chihuahuan Chickweed','Wynn Welldrake','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','California Compassplant','Xenia Burdge','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hypnaceae','Platydictya Moss','Gilberte Dowglass','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Broadbeard Beardtongue','Loise Sandhill','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Blackroot Sedge','Tally Smitherham','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Woodland Wild Coffee','Salim Engall','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Emperor''s Candlesticks','Weston Rennicks','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhamnaceae','Sonoma Ceanothus','Yolanthe Rowbottam','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Beach False Foxglove','Valry Fawcitt','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Hyssopus','Allina Sherlock','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Verbenaceae','Whitebrush','Mylo Bambrugh','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Goldenrod','Sven Barrow','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Green Sprangletop','Trula Castanone','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Finestem Needlegrass','Emilia Wemes','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Solanaceae','Bush-violet','Vitia Le Barre','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Cotoneaster','Hershel Outhwaite','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Diffuse Clover','Arabela Whall','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Orchidaceae','Big Cypress Star Orchid','Hillary Ingolotti','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Salicaceae','Balsam Willow','Burlie Wellbelove','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Hayden''s Clover','Olav Petracco','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Collemataceae','Texas Jelly Lichen','Robyn Frean','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Congo Coffee','Modesty Sprulls','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Hairy Fimbry','Osmund Harberer','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Primulaceae','Kokee Yellow Loosestrife','Gabbey MacNeillie','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Green Bulrush','Darcie Rowdell','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lentibulariaceae','Fringed Bladderwort','Silvan Domengue','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Congdon''s Milkvetch','Sharona Penrice','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Soerensen''s Sedge','Peterus Nunson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Purple Amaranth','Idette Dumberrill','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Little Green Sedge','Lianna Giles','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Orchidaceae','Dwarf Butterfly Orchid','Ameline Coveny','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Hairy Gumweed','Alexandros Cater','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Pentas','Olympe Houliston','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Rockface Starviolet','Barb Gusticke','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Brown Flatsedge','Zsa zsa MacAlpin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Clammy Clover','Jack Japp','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Helonias','Selina Towll','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Tamar Shallcross','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Palo Alto Thistle','Doris Jans','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Narrowleaf Cowwheat','Lindie Skehan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Sonoran Neststraw','Parrnell Vassall','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Hawthorn','Winnie Attle','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Northern Long Sedge','Alidia Toplin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Broadleaf Speedwell','Waldo Van Giffen','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Hoffmann''s Blacksnakeroot','Jasen Pound','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Garryaceae','Chaparral Silktassel','Oates Hawket','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Moraceae','Council Tree','Lyssa Mattock','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Antenoron','Noll Whitley','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Dipterocarpaceae','Shorea','May Clyne','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Copaiba','Neville Biernacki','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Jacob''s-ladder','Marjie Moan','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Ellipticleaf Cyanea','Magdalene Hamlyn','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Posidoniaceae','Posidonia','Kimberli Fishpond','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Jointed Spikesedge','Morly Barbosa','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Mojave Wildrye','Biron Ruppeli','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mustard','Dew Crippes','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Thornless Dewberry','Leonidas Lohden','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Iridaceae','Nevada Blue-eyed Grass','Serena MacSharry','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Slenderbeak Sedge','Ines Joslin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Manna Wattle','Travis Alcott','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Missouri Gourd','Aubrie Eubank','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Hyacinthbean','Latrina Schumacher','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Velvet Bean','Andrey Postles','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Pointed Gourd','Anson Blaasch','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Savory','Kellie Sirett','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Peirson''s Pincushion','Sharity Dooman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Parmeliaceae','Chiricahua Neofuscelia Lichen','Zonnya Paula','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Big Saltbush','Clair Whisson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Dwarf Suncup','Jesselyn Enga','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Clusiaceae','Hairy St. Johnswort','Blondell Foux','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Leatherstem','Eldon Corradi','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Brazos Rockcress','Jakob Coltherd','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Araliaceae','Angelica Tree','Nata Dubique','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Candelariaceae','Eggyolk Lichen','Royall Eaklee','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asclepiadaceae','Yellow Carolina Milkvine','Josi Huggins','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyclanthaceae','Carludovica','Gilberta Fitzhenry','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Composite Dropseed','Mord Schiefersten','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Badlands Mule-ears','Rockey Broinlich','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Aster','Marni Meeron','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Silky Lupine','Jabez Harcus','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Harsh Cyanea','Gerard Rudgley','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Agavaceae','Joshua Tree','Elberta Dwire','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Erpodiaceae','Solmsiella Moss','Merv Warwick','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Smallhead Beaksedge','Bertrando Schrieves','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Arizona Dewberry','Kayla Mustin','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','False Tick Trefoil','Angelia Chamberlaine','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Northern Idaho Biscuitroot','Deonne Mattschas','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Widewing Springparsley','Derwin Brian','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Convolvulaceae','Cardinal Climber','Michelina Serrurier','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Ibapah Tickweed','Mariel Dmitrienko','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Otholobium','Mona Lawther','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Cherokee Sedge','Nadia McEllen','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Mountain Spurge','Carmon Clapperton','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Curveseed Butterwort','Hadleigh Fike','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Cupgrass','Sheeree Bartolacci','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Forked Nailwort','Birgitta Veelers','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caprifoliaceae','Mountain Fly Honeysuckle','Barn L'' Estrange','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Helodiaceae','Blandow''s Helodium Moss','Locke Johnys','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','South American Skullcap','Shelton Cockill','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Juncaceae','Bayonet Rush','Tallie Birchenough','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Ballhead Ragwort','Anjela Harral','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Dioscoreaceae','Bush Yam','Sigismond Grange','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ophioglossaceae','Mingan Moonwort','Dick Dunnet','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Intermountain Bedstraw','Jillana Bernhart','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Monoblastiaceae','Anisomeridium Lichen','Celina Naulls','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Largeflower Fleabane','Jareb Clowley','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Rocky Mountain Buttercup','Johnna Perl','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Acarosporaceae','Sarcogyne Lichen','Terry MacPhail','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lauraceae','Sweetwood','Spense Diess','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Hispid Phyllostegia','Josi Cyphus','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Gentianaceae','Yukon Fringed Gentian','Emilio Essberger','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Disc Lichen','Ada Smithson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mediterranean Rocket','Kristian Tallyn','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Rockjasmine Monkeyflower','Evaleen Kunert','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Minnesota Fawnlily','Felita Snap','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arecaceae','Flynn''s Pritchardia','Stephan Gear','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Squirting Cucumber','Agretha Trimble','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Yerba Porosa','Torey Coode','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Menispermaceae','Cupseed','Kristofor Stewartson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pertusariaceae','Pore Lichen','Birgitta Gilmore','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Lecanora Disc Lichen','Luis De Atta','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mustard','Nicola Benettini','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Raymond''s Sedge','Dionysus Marchington','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Crassulaceae','Candleholder Liveforever','Emelina Cluelow','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arecaceae','Fountain Palm','Selena Cookman','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Dwarf Stickpea','Henka Catterill','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Crested Wheatgrass','Gwenette Scotson','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Bromeliaceae','Bulbous Airplant','Harrison Tellenbrok','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Narrowleaf Crucianella','Abraham Glencross','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caprifoliaceae','Black Elderberry','Novelia Martinets','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Iron Ipomopsis','Russell Hurndall','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Clovenfoot Plumegrass','Addison Clyma','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Convolvulaceae','Morningglory','Forest Wardlaw','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Na''ena''e Pua Melemele','Rhonda Mantrip','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hydrophyllaceae','White Fiestaflower','David Thurling','2','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ericaceae','Vine Hill Manzanita','Lissi Nowakowski','2','100')
