INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Vittariaceae','Tufted Lineleaf Fern','Ganny Broader','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Needlegrass','Tyne Karpfen','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Primulaceae','Cowslip Primrose','Silas Dartan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Shield Lichen','Jarid Thomsson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Godfry Trower','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lichinaceae','Thermutis Lichen','Chrisse Yate','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Fireweed','Anette Jorez','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Betulaceae','American Hornbeam','Maren Rattray','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Sematophyllaceae','Maryland Sematophyllum Moss','Shep Darlasson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arthopyreniaceae','Lyre Shell Lichen','Alexandro Pincked','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cactaceae','Cushion Foxtail Cactus','Kaitlin Shropshire','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Calycanthaceae','Eastern Sweetshrub','Celestina Joblin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hippocastanaceae','Japanese Horse Chestnut','Hogan Mockler','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fissidentaceae','Fissidens Moss','Nelson Trinder','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Haresfoot Locoweed','Ranice Kellick','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pedaliaceae','Escorzonera','Emlyn McIlvoray','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Talus Springparsley','Webster Dellatorre','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Field Blackberry','Lucretia Beddo','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Mountain Goldenbanner','Chase Messiter','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Axilflower','Court Cuchey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hydrocharitaceae','Brazilian Waterweed','Jdavie Van De Cappelle','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Cymbopogon Grass','Jackie Dodgshun','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Bog Yellowcress','Aeriell MacKeig','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Clasping Heliotrope','Mignonne Maddison','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Douglas'' Buckwheat','Lethia Kleinsmuntz','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apocynaceae','Trachelospermum','Odille Slocumb','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Ashe''s Calamint','Domini Torbet','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Bolander''s Mule-ears','Homer Breyt','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Kaffir Potato','Laurette Breissan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lichinaceae','Demangeon''s Phylliscum Lichen','Doris Kelloch','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Sneezeweed','Reagan Belham','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','White Bryony','Brigitta Dodman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Rinodina Lichen','Rosanna Galgey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','West Indian Sage','Chance Ficken','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Knotted Pearlwort','Nyssa Skirvane','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Yellow Gilia','Claudio Trenchard','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Crassulaceae','Nevius'' Stonecrop','Drucy Skillanders','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Rurik McLagain','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Big Chickweed','Jocelyn Shelf','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Mouse-ear Chickweed','Danell Kainz','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lobariaceae','Lung Lichen','Gaspard Kesteven','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Broadleaf Panicum','Mack Theseira','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhamnaceae','Urban''s Nakedwood','Brendis Millions','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Wreath Lichen','Abbie O''Heneghan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cuscutaceae','Cusp Dodder','Shep Scully','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Fringed Windmill Grass','Murvyn Cleynaert','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Elegant Zinnia','Idalina Bulley','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Spotted Beebalm','Jacky Oakland','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pteridaceae','Slender Brake','Gordie Westberg','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Goatgrass','Brooke Santorini','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Forked Hareleaf','Jamil Rodolico','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pyrenulaceae','Macoun''s Wart Lichen','Muire Worling','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Maize','Kim Spykings','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Geraniaceae','Veiny Geranium','Flossie Kneal','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Fonio','Thane Varns','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Magnoliaceae','Tuliptree','Alec Lesurf','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','White Thoroughwort','Tera Waterhowse','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Geraniaceae','Zonal Geranium','Zaria Artis','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Broadleaf Wild Leek','Neddy Headech','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Theaceae','Ternstroemia','Osbert MacGettigen','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Nepal Physciella','Levey Ribchester','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Lowland Blackberry','Sherm Nyland','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Porpidiaceae','Bellemerea Lichen','Sven Vouls','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Parry''s Mallow','Ebony Slisby','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Kauai Bur Cucumber','Bernadene Matieu','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Louisiana Goldenrod','Christalle Sweed','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Kenilworth Ivy','Ferne Furmenger','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fagaceae','Tanoak','Kally McIlenna','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Western Wallflower','Ado Mallock','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Portulacaceae','Brandegee''s Springbeauty','Mandy Lummasana','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Curly Dock','Alvie Everton','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Oleaceae','Devilwood','Kaiser Domenge','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Gibson''s Cyanea','Louella Strothers','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Urban''s Sandmat','Shena Bugg','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Missouri Milkvetch','Tristam Anelay','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Good King Henry','Rolando MacKaig','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Juda''s Bush','Wes Pocklington','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Moleplant','Sonja Cartin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Hardham''s Bedstraw','Holly-anne Brownell','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Indian Flatsedge','Cristiano Caulwell','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Field Sagewort','Marcela Murrigan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Capparaceae','Tropical Spiderflower','Miguela Lecordier','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Icacinaceae','Ngmui','Stormie Skiggs','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Hardheads','Nancee Huie','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pottiaceae','Acaulon Moss','Nev Dinesen','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Menispermaceae','Velvetleaf','Stefa Gibbe','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Pentaclethra','Borg Galbraith','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Hybrid Rose','Guglielma Ornelas','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Alpine Bittercress','Xylia Deverose','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Snow Arnica','Ripley Louiset','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Tropical Puff','Hendrick Casassa','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Rough Dubautia','Justino Epps','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Aleutian Brome','Melantha Kanter','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Melianthaceae','Melianthus','Sylas Dossit','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Arctic Rinodina Lichen','Ezmeralda Nunes Nabarro','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Urticaceae','Puerto Rico Clearweed','Cathi Meigh','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Brouard''s Rim Lichen','Rossie Dradey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Proatriplex','Read Duncan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Soft Goldenaster','Karina Norway','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Kamchatka Spikerush','Al Goodliffe','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Ecotone Blackberry','Anna-maria Muckloe','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Eggleaf Coraldrops','Evelin Wilcox','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Purple Poppymallow','Bartlett Mirfield','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brachytheciaceae','Nelson''s Brachythecium Moss','Maridel Rosone','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Iridaceae','Nuttall''s Pleatleaf','Leonanie Roach','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Hooker Bugseed','Rene Holstein','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Freckled Milkvetch','Wes Vipan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Pale Giant Hyssop','Efren Alldritt','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Woollypod Milkvetch','Riobard Roughsedge','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Panicled Sandmallow','Gates Pech','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Saltbush','Petey Scholcroft','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Kaibab Suncup','Noll Fourman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Malvaceae','Kern Mallow','Alis Anfrey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Florida Pineland Spurge','Norrie Rowsel','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cupressaceae','Western Juniper','Martin Golborn','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Theophrastaceae','Chirriador','Tessy Chyuerton','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Agavaceae','Indian Bowstring Hemp','Lauren Friel','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Siberian Dock','Bax Rouby','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Arctic Rattlebox','Broderick Luchelli','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Seaside Amaranth','Cob Noakes','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Cucubano','Kort Brastead','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Phytolaccaceae','Guinea Henweed','Clarke Flaxon','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Licorice Weed','Karil Sephton','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Western Sweetvetch','Randolph Van de Velde','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Kern Larkspur','Denny Stanbrooke','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pinaceae','Subalpine Fir','Sandra Lowey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Acarosporaceae','Sarcosagium Lichen','Gaston Satteford','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cuscutaceae','Trans-pecos Dodder','Mathe Spackman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhizocarpaceae','Distinct Map Lichen','Clarine Abbiss','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Lesser Hawkbit','Windham Tatlowe','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Portulacaceae','Streambank Springbeauty','Lawry McGoldrick','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Holm''s Reedgrass','Tova Sandwith','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Cotorrilla','Joel Van der Hoeven','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Capparaceae','Oxystylis','Lyell Rought','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Rubber Rabbitbrush','Georg Clayfield','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Low Silverbush','Alejandrina Gjerde','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Lone Fleabane','Rochella Desantis','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','American Plum','Holmes Bartoleyn','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Hebe','Clementine Noonan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Burrdock','Keslie Milne','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Soft Phlox','Malena Petrashkov','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Barbasco','Bryana Scotson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','False Spiraea','Cthrine Angliss','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Roving Sailor','Cobby Drillingcourt','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Myrtaceae','Guavaberry','Nicholle Eiler','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Porter''s Reedgrass','Trever Faires','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Solanaceae','Cypresshead Groundcherry','Shannon Blackledge','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Aspleniaceae','Pamohe','Stefania Robillart','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Reed','Othelia Trustey','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Oxalidaceae','Carambola','Jay Stringman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Myrtaceae','Burgan','Datha Plackstone','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Volcan''s Fuchsia','Schuyler Assad','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Chihuahuan Chickweed','Wynn Welldrake','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','California Compassplant','Xenia Burdge','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hypnaceae','Platydictya Moss','Gilberte Dowglass','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Broadbeard Beardtongue','Loise Sandhill','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Blackroot Sedge','Tally Smitherham','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Woodland Wild Coffee','Salim Engall','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Emperor''s Candlesticks','Weston Rennicks','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rhamnaceae','Sonoma Ceanothus','Yolanthe Rowbottam','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Beach False Foxglove','Valry Fawcitt','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Hyssopus','Allina Sherlock','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Verbenaceae','Whitebrush','Mylo Bambrugh','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Goldenrod','Sven Barrow','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Green Sprangletop','Trula Castanone','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Finestem Needlegrass','Emilia Wemes','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Solanaceae','Bush-violet','Vitia Le Barre','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Cotoneaster','Hershel Outhwaite','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Diffuse Clover','Arabela Whall','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Orchidaceae','Big Cypress Star Orchid','Hillary Ingolotti','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Salicaceae','Balsam Willow','Burlie Wellbelove','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Hayden''s Clover','Olav Petracco','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Collemataceae','Texas Jelly Lichen','Robyn Frean','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Congo Coffee','Modesty Sprulls','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Hairy Fimbry','Osmund Harberer','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Primulaceae','Kokee Yellow Loosestrife','Gabbey MacNeillie','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Green Bulrush','Darcie Rowdell','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lentibulariaceae','Fringed Bladderwort','Silvan Domengue','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Congdon''s Milkvetch','Sharona Penrice','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Soerensen''s Sedge','Peterus Nunson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Amaranthaceae','Purple Amaranth','Idette Dumberrill','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Little Green Sedge','Lianna Giles','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Orchidaceae','Dwarf Butterfly Orchid','Ameline Coveny','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Hairy Gumweed','Alexandros Cater','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Pentas','Olympe Houliston','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Rockface Starviolet','Barb Gusticke','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Brown Flatsedge','Zsa zsa MacAlpin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Clammy Clover','Jack Japp','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Helonias','Selina Towll','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lecanoraceae','Rim Lichen','Tamar Shallcross','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Palo Alto Thistle','Doris Jans','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Narrowleaf Cowwheat','Lindie Skehan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Sonoran Neststraw','Parrnell Vassall','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Hawthorn','Winnie Attle','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Northern Long Sedge','Alidia Toplin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Broadleaf Speedwell','Waldo Van Giffen','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Hoffmann''s Blacksnakeroot','Jasen Pound','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Garryaceae','Chaparral Silktassel','Oates Hawket','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Moraceae','Council Tree','Lyssa Mattock','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polygonaceae','Antenoron','Noll Whitley','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Dipterocarpaceae','Shorea','May Clyne','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Copaiba','Neville Biernacki','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Jacob''s-ladder','Marjie Moan','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Ellipticleaf Cyanea','Magdalene Hamlyn','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Posidoniaceae','Posidonia','Kimberli Fishpond','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Jointed Spikesedge','Morly Barbosa','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Mojave Wildrye','Biron Ruppeli','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mustard','Dew Crippes','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Thornless Dewberry','Leonidas Lohden','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Iridaceae','Nevada Blue-eyed Grass','Serena MacSharry','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Slenderbeak Sedge','Ines Joslin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Manna Wattle','Travis Alcott','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Missouri Gourd','Aubrie Eubank','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Hyacinthbean','Latrina Schumacher','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Velvet Bean','Andrey Postles','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Pointed Gourd','Anson Blaasch','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Savory','Kellie Sirett','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Peirson''s Pincushion','Sharity Dooman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Parmeliaceae','Chiricahua Neofuscelia Lichen','Zonnya Paula','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Chenopodiaceae','Big Saltbush','Clair Whisson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Onagraceae','Dwarf Suncup','Jesselyn Enga','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Clusiaceae','Hairy St. Johnswort','Blondell Foux','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Leatherstem','Eldon Corradi','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Brazos Rockcress','Jakob Coltherd','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Araliaceae','Angelica Tree','Nata Dubique','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Candelariaceae','Eggyolk Lichen','Royall Eaklee','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asclepiadaceae','Yellow Carolina Milkvine','Josi Huggins','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyclanthaceae','Carludovica','Gilberta Fitzhenry','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Composite Dropseed','Mord Schiefersten','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Badlands Mule-ears','Rockey Broinlich','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Aster','Marni Meeron','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Silky Lupine','Jabez Harcus','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Campanulaceae','Harsh Cyanea','Gerard Rudgley','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Agavaceae','Joshua Tree','Elberta Dwire','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Erpodiaceae','Solmsiella Moss','Merv Warwick','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Smallhead Beaksedge','Bertrando Schrieves','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rosaceae','Arizona Dewberry','Kayla Mustin','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','False Tick Trefoil','Angelia Chamberlaine','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Northern Idaho Biscuitroot','Deonne Mattschas','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Apiaceae','Widewing Springparsley','Derwin Brian','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Convolvulaceae','Cardinal Climber','Michelina Serrurier','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Boraginaceae','Ibapah Tickweed','Mariel Dmitrienko','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Otholobium','Mona Lawther','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Cherokee Sedge','Nadia McEllen','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Euphorbiaceae','Mountain Spurge','Carmon Clapperton','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Curveseed Butterwort','Hadleigh Fike','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Cupgrass','Sheeree Bartolacci','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caryophyllaceae','Forked Nailwort','Birgitta Veelers','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caprifoliaceae','Mountain Fly Honeysuckle','Barn L'' Estrange','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Helodiaceae','Blandow''s Helodium Moss','Locke Johnys','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','South American Skullcap','Shelton Cockill','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Juncaceae','Bayonet Rush','Tallie Birchenough','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Ballhead Ragwort','Anjela Harral','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Dioscoreaceae','Bush Yam','Sigismond Grange','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ophioglossaceae','Mingan Moonwort','Dick Dunnet','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Intermountain Bedstraw','Jillana Bernhart','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Monoblastiaceae','Anisomeridium Lichen','Celina Naulls','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Largeflower Fleabane','Jareb Clowley','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ranunculaceae','Rocky Mountain Buttercup','Johnna Perl','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Acarosporaceae','Sarcogyne Lichen','Terry MacPhail','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lauraceae','Sweetwood','Spense Diess','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Lamiaceae','Hispid Phyllostegia','Josi Cyphus','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Gentianaceae','Yukon Fringed Gentian','Emilio Essberger','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Disc Lichen','Ada Smithson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mediterranean Rocket','Kristian Tallyn','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Scrophulariaceae','Rockjasmine Monkeyflower','Evaleen Kunert','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Liliaceae','Minnesota Fawnlily','Felita Snap','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arecaceae','Flynn''s Pritchardia','Stephan Gear','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cucurbitaceae','Squirting Cucumber','Agretha Trimble','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Yerba Porosa','Torey Coode','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Menispermaceae','Cupseed','Kristofor Stewartson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Pertusariaceae','Pore Lichen','Birgitta Gilmore','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Physciaceae','Lecanora Disc Lichen','Luis De Atta','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Brassicaceae','Mustard','Nicola Benettini','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Cyperaceae','Raymond''s Sedge','Dionysus Marchington','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Crassulaceae','Candleholder Liveforever','Emelina Cluelow','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Arecaceae','Fountain Palm','Selena Cookman','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Fabaceae','Dwarf Stickpea','Henka Catterill','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Crested Wheatgrass','Gwenette Scotson','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Bromeliaceae','Bulbous Airplant','Harrison Tellenbrok','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Rubiaceae','Narrowleaf Crucianella','Abraham Glencross','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Caprifoliaceae','Black Elderberry','Novelia Martinets','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Polemoniaceae','Iron Ipomopsis','Russell Hurndall','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Poaceae','Clovenfoot Plumegrass','Addison Clyma','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Convolvulaceae','Morningglory','Forest Wardlaw','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Asteraceae','Na''ena''e Pua Melemele','Rhonda Mantrip','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Hydrophyllaceae','White Fiestaflower','David Thurling','02:00:00','100')
INSERT INTO Workshops (WorkshopName, WorkshopDescription, Mentor, Duration, Price)
VALUES('Ericaceae','Vine Hill Manzanita','Lissi Nowakowski','02:00:00','100')
